import { useEffect, useMemo, useState } from "react";
import "@/App.css";
import axios from "axios";
import { ArrowDownLeft, ArrowUpRight, Boxes, Camera, ChevronDown, CircleDollarSign, ClipboardList, History, LayoutDashboard, Menu, PieChart, Plus, Search, ShoppingCart, Store, X } from "lucide-react";
import { toast, Toaster } from "sonner";
import { HistoryView } from "@/components/HistoryView";
import { ReportsView } from "@/components/ReportsView";
import { StockView } from "@/components/StockView";

const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
const API = `${BACKEND_URL}/api`;

const money = (n) => `Rp ${Number(n || 0).toLocaleString("id-ID", { maximumFractionDigits: 0 })}`;

const Home = () => {
  const [products, setProducts] = useState([]), [transactions, setTransactions] = useState([]), [summary, setSummary] = useState({}), [modal, setModal] = useState(null), [query, setQuery] = useState(""), [mobileOpen, setMobileOpen] = useState(false), [view, setView] = useState("overview");
  const [form, setForm] = useState({ type: "sale", product_id: "", quantity: 1, unit_price: "", note: "", proof_image: null });
  const load = async () => { const [p, t, s] = await Promise.all([axios.get(`${API}/products`), axios.get(`${API}/transactions`), axios.get(`${API}/summary`)]); setProducts(p.data); setTransactions(t.data); setSummary(s.data); };
  useEffect(() => { load().catch(() => toast.error("Could not load your store data")); }, []);
  const filtered = useMemo(() => products.filter(p => p.name.toLowerCase().includes(query.toLowerCase()) || p.category.toLowerCase().includes(query.toLowerCase())), [products, query]);
  const openForm = (type) => { setForm({ type, product_id: products[0]?.id || "", quantity: 1, unit_price: type === "sale" ? products[0]?.selling_price : products[0]?.cost_price, note: "", proof_image: null }); setModal(type); };
  const submit = async (e) => { e.preventDefault(); try { await axios.post(`${API}/transactions`, { ...form, quantity: Number(form.quantity), unit_price: Number(form.unit_price) }); toast.success(`${form.type === "sale" ? "Sale" : "Purchase"} recorded`); setModal(null); load(); } catch (err) { toast.error(err.response?.data?.detail || "Please check the details"); } };
  const selectProduct = (id) => { const p = products.find(x => x.id === id); setForm({ ...form, product_id: id, unit_price: form.type === "sale" ? p.selling_price : p.cost_price }); };

  const todayLabel = new Intl.DateTimeFormat("en-US", { weekday: "long", day: "numeric", month: "long", year: "numeric" }).format(new Date()).toUpperCase();
  return <div className="app-shell"><Toaster position="top-right" richColors />
    <aside className={`sidebar ${mobileOpen ? "open" : ""}`}><div className="brand"><span className="brand-mark"><Store size={19}/></span><span>GreenBasket</span><button className="close-mobile" data-testid="close-mobile-menu" onClick={() => setMobileOpen(false)}><X size={18}/></button></div><p className="store-label">STORE OPERATIONS</p><nav><button className={`nav-item ${view === "overview" ? "active" : ""}`} data-testid="dashboard-nav" onClick={() => { setView("overview"); setMobileOpen(false); load(); }}><LayoutDashboard size={18}/> Overview</button><button className={`nav-item ${view === "stock" ? "active" : ""}`} data-testid="stock-nav" onClick={() => { setView("stock"); setMobileOpen(false); }}><Boxes size={18}/> Stock</button><button className={`nav-item ${view === "history" ? "active" : ""}`} data-testid="history-nav" onClick={() => { setView("history"); setMobileOpen(false); }}><History size={18}/> History</button><button className={`nav-item ${view === "reports" ? "active" : ""}`} data-testid="reports-nav" onClick={() => { setView("reports"); setMobileOpen(false); }}><PieChart size={18}/> Reports</button></nav><div className="sidebar-bottom"><div className="status-dot"/> Store open <span className="chevron"><ChevronDown size={15}/></span></div></aside>
    <main className="main"><header className="topbar"><button className="mobile-menu" data-testid="open-mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={20}/></button><div><p className="eyebrow">{todayLabel}</p><h1>Good morning, manager</h1></div><div className="top-actions"><div className="avatar" data-testid="user-avatar">AM</div></div></header>
      {view === "overview" && <section className="content"><div className="intro"><div><p className="eyebrow green">TODAY AT A GLANCE</p><h2>Keep your shelves moving.</h2><p className="subcopy">A clear view of what’s in stock and where your cash is going.</p></div><div className="quick-actions"><button className="btn secondary" data-testid="record-purchase-button" onClick={() => openForm("purchase")}><ArrowDownLeft size={16}/> Record purchase</button><button className="btn primary" data-testid="record-sale-button" onClick={() => openForm("sale")}><ArrowUpRight size={16}/> Record sale</button></div></div>
        <div className="stat-grid"><div className="stat-card"><div className="stat-label">CASH FLOW <span className="stat-icon green-icon"><CircleDollarSign size={17}/></span></div><strong className={summary.cash_flow < 0 ? "negative" : ""}>{money(summary.cash_flow)}</strong><span className="stat-note">Sales less purchases</span></div><div className="stat-card"><div className="stat-label">TOTAL STOCK <span className="stat-icon blue-icon"><Boxes size={17}/></span></div><strong>{summary.stock_units || 0}</strong><span className="stat-note">Units across {summary.products || 0} products</span></div><div className="stat-card"><div className="stat-label">SALES TODAY <span className="stat-icon amber-icon"><ArrowUpRight size={17}/></span></div><strong>{money(summary.sales_today)}</strong><span className="stat-note">{summary.sales_today_count || 0} transactions</span></div><div className="stat-card alert-card"><div className="stat-label">LOW STOCK <span className="stat-icon red-icon"><ClipboardList size={17}/></span></div><strong>{summary.low_stock || 0}</strong><span className="stat-note">Need your attention</span></div></div>
        <div className="workspace-grid"><section className="panel inventory-panel"><div className="panel-head"><div><h3>Inventory snapshot</h3><p>Live stock levels by product</p></div><div className="search"><Search size={16}/><input data-testid="inventory-search-input" placeholder="Search products" value={query} onChange={e => setQuery(e.target.value)}/></div></div><div className="table-wrap"><table><thead><tr><th>PRODUCT</th><th>CATEGORY</th><th>IN STOCK</th><th>SELLING PRICE</th><th>STATUS</th></tr></thead><tbody>{filtered.map(p => <tr key={p.id}><td><div className="product-name"><span className="product-letter">{p.name[0]}</span><span>{p.name}<small>per {p.unit}</small></span></div></td><td><span className="category">{p.category}</span></td><td><b>{p.stock}</b> <span className="muted">{p.unit}s</span></td><td>{money(p.selling_price)}</td><td><span className={`stock-status ${p.stock <= p.reorder_level ? "low" : "good"}`}>{p.stock <= p.reorder_level ? "Low stock" : "In stock"}</span></td></tr>)}</tbody></table></div></section>
        <section className="panel activity-panel"><div className="panel-head"><div><h3>Recent activity</h3><p>Your latest store movements</p></div><button className="icon-button" data-testid="refresh-activity-button" onClick={load}>↻</button></div><div className="activity-list">{transactions.slice(0, 5).map(t => <div className="activity" key={t.id}><span className={`activity-icon ${t.type}`} >{t.type === "sale" ? <ArrowUpRight size={16}/> : <ArrowDownLeft size={16}/>}</span><div><b>{t.type === "sale" ? "Sale" : "Purchase"} · {t.product_name}</b><small>{t.quantity} units · {new Date(t.created_at).toLocaleDateString()}</small></div><strong className={t.type === "sale" ? "positive" : "negative"}>{t.type === "sale" ? "+" : "−"}{money(t.total)}</strong></div>)}{!transactions.length && <div className="empty">No movements recorded yet.</div>}</div></section></div>
      </section>}
      {view === "stock" && <StockView />}
      {view === "history" && <HistoryView />}
      {view === "reports" && <ReportsView />}
    </main>
    {modal && <div className="modal-backdrop" data-testid="transaction-modal"><form className="modal" onSubmit={submit}><div className="modal-head"><div><p className="eyebrow green">NEW MOVEMENT</p><h3>Record a {modal}</h3></div><button type="button" className="icon-button" data-testid="close-transaction-modal" onClick={() => setModal(null)}><X size={18}/></button></div><label>Product<select data-testid="transaction-product-select" value={form.product_id} onChange={e => selectProduct(e.target.value)}>{products.map(p => <option key={p.id} value={p.id}>{p.name} · {p.stock} in stock</option>)}</select></label><div className="form-row"><label>Quantity<input data-testid="transaction-quantity-input" type="number" min="1" value={form.quantity} onChange={e => setForm({...form, quantity: e.target.value})}/></label><label>Unit price<input data-testid="transaction-price-input" type="number" min="0" step="0.01" value={form.unit_price} onChange={e => setForm({...form, unit_price: e.target.value})}/></label></div><label>Note <span className="optional">optional</span><input data-testid="transaction-note-input" placeholder="e.g. Supplier invoice 104" value={form.note} onChange={e => setForm({...form, note: e.target.value})}/></label><label className="proof-upload"><span>Payment proof <span className="optional">optional</span></span><input data-testid="payment-proof-input" type="file" accept="image/*" onChange={e => { const file=e.target.files[0]; if(file){ const reader=new FileReader(); reader.onload=()=>setForm({...form, proof_image: reader.result}); reader.readAsDataURL(file); }}}/><span className="upload-box"><Camera size={18}/> {form.proof_image ? "Image attached" : "Attach receipt or payment screenshot"}</span></label><button className="btn primary full" data-testid="submit-transaction-button" type="submit"><Plus size={16}/> Save {modal}</button></form></div>}
  </div>;
};

function App() { return <Home />; }

export default App;
